AppBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        string:
            type: string
            length: 255
            unique: true
        telephone:
            type: string
            length: 255
            unique: true
        site:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
    lifecycleCallbacks: {  }
